export const Strings = {
  vi: {
    value: "vi",
    tableStatus: {
      all: "Tất cả",
      available: "Trống",
      occupied: "Đang phục vụ",
      reserved: "Đã đặt",
      canceled: "Đã hủy",
    },
    tableManagementPage: {
      title: "Danh sách bàn",
    },
    text: {
      admin: "Quản lý",
      capacity: "Sức chứa",
      guest: "khách",
      threeDot: "...",
      twoDot: ":",
      hyphen: "-",
      blank: "",
      HHmm: "HH:mm",
      HHmmss: "HH:mm:ss",
      numberLocale: "vi-VN",
      currencySuffix: "đ",

      restaurantName: "Hải Sản Biển Việt",
      restaurantSubtitle: "Nhà hàng hải sản",
      kaiten: "Hải Sản Biển Việt",
      seafoodRestaurant: "Nhà hàng hải sản",

      dashboard: "Trang chủ",
      tables: "Bàn",
      orders: "Đơn hàng",
      menu: "Món ăn",
      kitchen: "Bếp",
      payments: "Thanh toán",
      reports: "Thống kê",

      all: "Tất cả",
      searchTableInput: "Tìm bàn...",
      start: "Bắt đầu",
      close: "Đóng",
      cancel: "Hủy",
      save: "Lưu",
      confirm: "Xác nhận",
      status: "Trạng thái",
      note: "Ghi chú",
      none: "Chưa có",
      loading: "Đang tải...",

      tableList: "Danh sách bàn",
      allTables: "Tất cả",
      availableTables: "Trống",
      occupiedTables: "Đang phục vụ",
      reservedTables: "Đã đặt",
      canceledTables: "Đã hủy",
      tableReady: "Sẵn sàng mở bàn",
      tableAvailableTitle: "Bàn đang trống",
      reservedTableTitle: "Bàn đã đặt trước",
      noSelectedTableTitle: "Chưa chọn bàn",
      noSelectedTableDescription: "Chọn một bàn trong danh sách để xem trạng thái, đơn hàng và thao tác.",
      chooseTableFromList: "Chọn bàn từ danh sách",
      noOpenOrderDescription: "Chưa có đơn hàng đang mở. Nhân viên có thể mở bàn ngay hoặc tạo lịch đặt trước cho khách.",
      processingStatus: "Trạng thái xử lý",
      notServed: "Chưa phục vụ",
      openTable: "Mở bàn",
      reserveTable: "Đặt trước",
      reserveTableTitle: "Đặt trước bàn",
      reservationInstruction: "Nhập thông tin khách để giữ bàn. Bàn chuyển sang trạng thái Đã đặt sau khi xác nhận.",
      confirmReservation: "Xác nhận đặt",
      reservationHoldDescription: "Giữ bàn cho khách. Chỉ tạo đơn hàng khi khách đến và nhân viên nhấn Nhận bàn.",
      receiveTable: "Nhận bàn",
      receiveTableTitle: "Nhận bàn?",
      receiveTableDescription: "Khi xác nhận, hệ thống chuyển bàn từ Đã đặt sang Đang phục vụ và tạo đơn hàng mới cho bàn này.",
      changeTable: "Đổi bàn",
      changeReservedTable: "Đổi bàn đặt trước",
      changeReservedTableDescription: "Chọn bàn trống khác cho khách. Bàn cũ sẽ trở về Trống, bàn mới chuyển sang Đã đặt.",
      currentTable: "Bàn hiện tại",
      newTable: "Bàn mới",
      suggestedTables: "Gợi ý",
      reason: "Lý do",
      confirmChange: "Xác nhận đổi",
      cancelReservation: "Hủy đặt bàn",
      cancelReservationTitle: "Hủy đặt bàn?",
      cancelReservationDescription: "Thao tác này hủy lịch đặt trước và đưa bàn về trạng thái Trống. Không tạo đơn hàng.",

      customer: "Khách",
      customerName: "Tên khách",
      phoneNumber: "Số điện thoại",
      guestCount: "Số khách",
      reservationTime: "Thời gian đặt",
      bookingTime: "Giờ đặt",
      bookedAt: "Đặt lúc",

      orderInf: "Thông tin đơn hàng",
      orderInfo: "Thông tin đơn hàng",
      orderInfoShort: "Thông tin đơn",
      currentOrder: "Đơn hiện tại",
      orderCode: "Mã đơn",
      noCurrentOrder: "Bàn chưa có đơn hàng đang mở.",
      createOrder: "Tạo đơn",
      viewOrder: "Xem đơn hàng",
      addDish: "Thêm món",
      addingDish: "Đang thêm...",
      dishCodePrefix: "Món #",
      dish: "Món",
      dishDetail: "Chi tiết món",
      quantity: "Số lượng",
      quantityShort: "SL",
      noOrderItems: "Chưa có món trong đơn.",
      sendToKitchen: "Gửi bếp",
      mergeTable: "Gộp bàn",

      tempCalculate: "Tạm tính",
      subtotal: "Tạm tính",
      totalSubtotal: "Tổng tạm tính",
      discount: "Giảm giá",
      total: "Tổng cộng",
      totalAmount: "Tổng tiền",
      totalPayment: "Tổng thanh toán",
      amountToCollect: "Cần thu",
      serviceFee: "Phí phục vụ",
      paymentMethod: "Phương thức",
      pay: "Thanh toán",
      payingOrder: "Đang thanh toán...",
      confirmPayment: "Xác nhận thanh toán",
      pendingOrderPaymentWarning: "Đơn đang chờ xác nhận món, chưa thể thanh toán.",
      cash: "Tiền mặt",
      banking: "Chuyển khoản",
      bankTransfer: "Chuyển khoản",
      momo: "Momo",
      servedBy: "Phục vụ",
      atTime: "Vào lúc",

      kitchenBoard: "Bếp - Kitchen board",
      ready: "Sẵn sàng",
      cooking: "Đang nấu",
      served: "Đã phục vụ",
      confirmStatus: "Xác nhận",

      menuManagement: "Quản lý món",
      menuAndReports: "Quản lý món và báo cáo",
      addEditDish: "Thêm / Sửa món",
      dishName: "Tên món",
      description: "Mô tả",
      category: "Danh mục",
      salePrice: "Giá bán",
      selling: "Đang bán",

      liveSeafood: "Hải sản sống",
      shrimp: "Tôm",
      squid: "Mực",
      crab: "Ghẹ - Cua",
      drinks: "Đồ uống",
      lobsterSteamed: "Tôm hùm hấp",
      beerSteamedCrab: "Ghẹ hấp bia",
      grilledSquidChiliSalt: "Mực nướng muối ớt",
      garlicButterSnails: "Ốc hương xào bơ tỏi",
      seafoodFriedRice: "Cơm chiên hải sản",
      garlicWaterSpinach: "Rau muống xào tỏi",
      tigerBeer: "Bia Tiger",
      bottledWater: "Nước suối",
      soySteamedFish: "Cá mú hấp xì dầu",

      reportsTitle: "Báo cáo",
      revenue: "Doanh thu",
      revenueByCategory: "Doanh thu theo danh mục",
      revenueByHour: "Doanh thu theo giờ",
      orderCount: "Đơn hàng",
      averageOrderValue: "Giá trị TB",
      averageGuests: "Khách TB",
      topSellingDishes: "Top 5 món bán chạy",

      fetchDishesError: "Không lấy được danh sách món",
      createOrderError: "Không thể tạo đơn hàng",
      payOrderError: "Không thể thanh toán đơn hàng",
      fetchTableError: "Không lấy được thông tin bàn",
      fetchTablesError: "Không lấy được danh sách bàn",
      addDishError: "Không thể thêm món",
      addReservationError: "Không thể đặt bàn trước",
      invalidReservationTimeError: "Thời gian đặt bàn không hợp lệ",
      fetchOrderItemTotalError: "Không lấy được tổng tiền OrderItem",
      fetchOrderItemsError: "Không lấy được thông tin OrderItem",
      fetchOrdersError: "Không lấy được danh sách đơn hàng",

      zeroString: "0",
      oneString: "1",
      twoString: "2",
      threeString: "3",
      fourString: "4",
      fiveString: "5",
      sixString: "6",
      sevenString: "7",
      eightString: "8",
      nineString: "9",
      tenString: "10",

      twelveString: "12",
      fourteenString: "14",
      sixteenString: "16",
      eighteenString: "18",
      twentyString: "20",
      twentyFourString: "24",
      thirtyString: "30",
      thirtyTwoString: "32",
      fortyString: "40",
      fortyEightString: "48",
      fiftyString: "50",
      sixtyString: "60",
      sixtyFourString: "64",
      eightyString: "80",
      oneHundredString: "100",

      negativeOneString: "-1",
      halfString: "0.5",
      fullString: "1",
    }
  },
  en: {
    value: "en",
    tableStatus: {
      all: "All",
      available: "Available",
      occupied: "Occupied",
      reserved: "Reserved",
      canceled: "Canceled",
    },
    tableManagementPage: {
      title: "Table list",
    },
    text: {
      admin: "Admin",
      capacity: "Capacity",
      guest: "guest",
      threeDot: "...",
      twoDot: ":",
      hyphen: "-",
      blank: "",
      HHmm: "HH:mm",
      HHmmss: "HH:mm:ss",
      numberLocale: "en-US",
      currencySuffix: "VND",

      restaurantName: "Bien Viet Seafood",
      restaurantSubtitle: "Seafood restaurant",
      kaiten: "Bien Viet Seafood",
      seafoodRestaurant: "Seafood restaurant",

      dashboard: "Dashboard",
      tables: "Tables",
      orders: "Orders",
      menu: "Menu",
      kitchen: "Kitchen",
      payments: "Payments",
      reports: "Reports",

      all: "All",
      searchTableInput: "Search table...",
      start: "Start",
      close: "Close",
      cancel: "Cancel",
      save: "Save",
      confirm: "Confirm",
      status: "Status",
      note: "Note",
      none: "None",
      loading: "Loading...",

      tableList: "Table list",
      allTables: "All",
      availableTables: "Available",
      occupiedTables: "Occupied",
      reservedTables: "Reserved",
      canceledTables: "Canceled",
      tableReady: "Ready to open table",
      tableAvailableTitle: "Available table",
      reservedTableTitle: "Reserved table",
      noSelectedTableTitle: "No table selected",
      noSelectedTableDescription: "Choose a table from the list to view status, orders, and actions.",
      chooseTableFromList: "Choose a table from the list",
      noOpenOrderDescription: "There is no open order. Staff can open the table now or create a reservation for guests.",
      processingStatus: "Processing status",
      notServed: "Not served",
      openTable: "Open table",
      reserveTable: "Reserve",
      reserveTableTitle: "Reserve table",
      reservationInstruction: "Enter guest information to hold the table. The table will move to Reserved after confirmation.",
      confirmReservation: "Confirm reservation",
      reservationHoldDescription: "Hold the table for guests. Only create an order when guests arrive and staff confirm the table.",
      receiveTable: "Seat guests",
      receiveTableTitle: "Seat guests?",
      receiveTableDescription: "After confirmation, the table moves from Reserved to Occupied and a new order is created for this table.",
      changeTable: "Change table",
      changeReservedTable: "Change reserved table",
      changeReservedTableDescription: "Choose another available table for the guests. The old table returns to Available and the new table becomes Reserved.",
      currentTable: "Current table",
      newTable: "New table",
      suggestedTables: "Suggestions",
      reason: "Reason",
      confirmChange: "Confirm change",
      cancelReservation: "Cancel reservation",
      cancelReservationTitle: "Cancel reservation?",
      cancelReservationDescription: "This cancels the reservation and returns the table to Available. No order will be created.",

      customer: "Guest",
      customerName: "Guest name",
      phoneNumber: "Phone number",
      guestCount: "Guests",
      reservationTime: "Reservation time",
      bookingTime: "Booking time",
      bookedAt: "Booked at",

      orderInf: "Order information",
      orderInfo: "Order information",
      orderInfoShort: "Order info",
      currentOrder: "Current order",
      orderCode: "Order ID",
      noCurrentOrder: "This table has no open order.",
      createOrder: "Create order",
      viewOrder: "View order",
      addDish: "Add dish",
      addingDish: "Adding...",
      dishCodePrefix: "Dish #",
      dish: "Dish",
      dishDetail: "Dish detail",
      quantity: "Quantity",
      quantityShort: "Qty",
      noOrderItems: "No dishes in this order.",
      sendToKitchen: "Send to kitchen",
      mergeTable: "Merge table",

      tempCalculate: "Subtotal",
      subtotal: "Subtotal",
      totalSubtotal: "Total subtotal",
      discount: "Discount",
      total: "Total",
      totalAmount: "Total amount",
      totalPayment: "Total payment",
      amountToCollect: "Amount due",
      serviceFee: "Service fee",
      paymentMethod: "Payment method",
      pay: "Pay",
      payingOrder: "Paying...",
      confirmPayment: "Confirm payment",
      pendingOrderPaymentWarning: "This order has pending dishes and cannot be paid yet.",
      cash: "Cash",
      banking: "Bank transfer",
      bankTransfer: "Bank transfer",
      momo: "Momo",
      servedBy: "Served by",
      atTime: "At",

      kitchenBoard: "Kitchen board",
      ready: "Ready",
      cooking: "Cooking",
      served: "Served",
      confirmStatus: "Confirm",

      menuManagement: "Menu management",
      menuAndReports: "Menu management and reports",
      addEditDish: "Add / Edit dish",
      dishName: "Dish name",
      description: "Description",
      category: "Category",
      salePrice: "Sale price",
      selling: "Selling",

      liveSeafood: "Live seafood",
      shrimp: "Shrimp",
      squid: "Squid",
      crab: "Crab",
      drinks: "Drinks",
      lobsterSteamed: "Steamed lobster",
      beerSteamedCrab: "Beer-steamed crab",
      grilledSquidChiliSalt: "Grilled squid with chili salt",
      garlicButterSnails: "Garlic butter snails",
      seafoodFriedRice: "Seafood fried rice",
      garlicWaterSpinach: "Garlic water spinach",
      tigerBeer: "Tiger beer",
      bottledWater: "Bottled water",
      soySteamedFish: "Soy-steamed grouper",

      reportsTitle: "Reports",
      revenue: "Revenue",
      revenueByCategory: "Revenue by category",
      revenueByHour: "Revenue by hour",
      orderCount: "Orders",
      averageOrderValue: "Avg. value",
      averageGuests: "Avg. guests",
      topSellingDishes: "Top 5 best-selling dishes",

      fetchDishesError: "Could not fetch dishes",
      createOrderError: "Could not create order",
      payOrderError: "Could not pay order",
      fetchTableError: "Could not fetch table information",
      fetchTablesError: "Could not fetch table list",
      addDishError: "Could not add dish",
      addReservationError: "Could not create reservation",
      invalidReservationTimeError: "Invalid reservation time",
      fetchOrderItemTotalError: "Could not fetch order item total",
      fetchOrderItemsError: "Could not fetch order items",
      fetchOrdersError: "Could not fetch orders",

      zeroString: "0",
      oneString: "1",
      twoString: "2",
      threeString: "3",
      fourString: "4",
      fiveString: "5",
      sixString: "6",
      sevenString: "7",
      eightString: "8",
      nineString: "9",
      tenString: "10",

      twelveString: "12",
      fourteenString: "14",
      sixteenString: "16",
      eighteenString: "18",
      twentyString: "20",
      twentyFourString: "24",
      thirtyString: "30",
      thirtyTwoString: "32",
      fortyString: "40",
      fortyEightString: "48",
      fiftyString: "50",
      sixtyString: "60",
      sixtyFourString: "64",
      eightyString: "80",
      oneHundredString: "100",

      negativeOneString: "-1",
      halfString: "0.5",
      fullString: "1",
    }
  },
} as const;
