
export const Strings = {
  vi: {
    tableStatus: {
      all: "Tất cả",
      available: "Trống",
      occupied: "Đang phục vụ",
      reserved: "Đã đặt",
    },
    tableManagementPage: {
      title: "Danh sách bàn",
    },
    text: {
      admin: "Quản lý",
      capacity: "Sức chứa",
      guest: "khách",
      threeDot: "...",
      twoDot: ":",
      hyphen: "-",
      searchTableInput: "Tìm bàn...",
      start: "Bắt đầu",
      orderInf: "Thông tin đơn hàng",
      tempCalculate: "Tạm tính",
      discount: "Giảm giá",
      total: "Tổng cộng",
      viewOrder: "Xem đơn hàng",
      addDish: "Thêm món",
      pay: "Thanh toán",
      kaiten: "Kai Ten",
      seafoodRestaurant: "Nhà hàng hải sản",
      dashboard: "Trang chủ",
      tables: "Bàn",
      orders: "Đơn hàng",
      menu: "Món ăn",
      kitchen: "Bếp",
      payments: "Thanh toán",
      reports: "Thống kê",
      blank: "",
      HHmm: "HH:mm",
      HHmmss: "HH:mm:ss",
    }
  },
  en: {
    tableStatus: {
      all: "All",
      available: "Available",
      occupied: "Occupied",
      reserved: "Reserved",
    },
    tableManagementPage: {
      title: "Table list ",
    },
    text: {
      admin: "Admin",
      capacity: "Capacity",
      guest: "guest",
      threeDot: "...",
      twoDot: ":",
      hyphen: "-",
      searchTableInput: "Search table...",
      start: "Start",
      orderInf: "Order info",
      tempCalculate: "Temporarily calculated",
      discount: "Discount",
      total: "Total",
      viewOrder: "View order",
      addDish: "Add dish",
      pay: "Pay",
      kaiten: "KAITEN",
      seafoodRestaurant: "Seafood restaurant",
      dashboard: "Dashboard",
      tables: "Tables",
      orders: "Orders",
      menu: "Menu",
      kitchen: "Kitchen",
      payments: "Payments",
      reports: "Reports",
      blank: "",
    }
  },
} as const;